export const header1 = 'Primary header (H2)'
export const header2 = 'Secondary header (H3)'
export const quote = "And this is your article template's pull quote — Storipress"

export const paragraphs = [
  'This is your body text. Customise me by clicking me and navigating to the context menu on the top left. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fermentum orci lacinia elementum pretium. Proin ac ullamcorper turpis. Proin fringilla ultrices tellus ut vulputate. Phasellus egestas massa vel sapien cursus, vitae sodales mi eleifend. Sed maximus, turpis id accumsan laoreet, augue leo vestibulum tellus, quis faucibus lorem mi eget magna. Pellentesque quis est mattis, accumsan dolor vitae, maximus dui. Quisque egestas ac odio elementum accumsan. Etiam lobortis volutpat nunc quis cursus. Duis gravida dapibus nulla at aliquet. Vestibulum dapibus eros eget tincidunt aliquet. Aenean et porttitor nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec eu leo sed nulla interdum facilisis.',
  'Etiam at faucibus ex. Suspendisse a placerat mauris. Nam vel vulputate tortor, vitae sodales velit. Sed at dolor ex. Ut consectetur sem vel ligula volutpat vulputate. Fusce venenatis, odio vitae dictum pellentesque, ex nibh tempor libero, eget congue risus odio id quam. Pellentesque aliquet lorem at ipsum dictum dignissim. Duis nec sagittis magna. Pellentesque accumsan, dui sit amet mollis vestibulum, neque nibh pellentesque nisl, quis bibendum eros nisi et dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'Sed pellentesque consequat tellus eget laoreet. Nam fermentum, ipsum at mollis pharetra, nisl risus pellentesque nisl, sit amet volutpat purus tortor vel tortor. Etiam ac suscipit ante. Sed augue nisl, sagittis in felis eu, volutpat efficitur est. Maecenas nisi nunc, laoreet sit amet purus sed, aliquam elementum ligula. Vivamus ut ante tortor. Suspendisse auctor vel leo id venenatis. Cras diam arcu, tempus vel lectus quis, facilisis maximus tortor. Duis imperdiet vel augue eu hendrerit. Sed gravida ante sit amet quam pellentesque, in gravida nunc suscipit. Vivamus laoreet tincidunt eros, in pharetra purus pulvinar id. Sed tristique molestie ullamcorper. Sed aliquet metus sit amet ultricies feugiat. Ut ullamcorper blandit neque at porttitor. Praesent at arcu nec odio viverra ultricies non nec odio.',
  'Morbi tristique eros blandit laoreet faucibus. Sed risus augue, congue eget mi nec, rhoncus suscipit urna. Suspendisse feugiat dui in dapibus posuere. Quisque lectus quam, finibus nec sodales eu, auctor in ex. Aliquam vulputate semper nulla ut pretium. Nunc metus neque, posuere sed sodales ut, lacinia quis nibh. Integer vitae libero in nisi gravida luctus sed eu ipsum. Nam a fermentum nunc. Quisque sed ipsum a ex rutrum convallis. Curabitur tempor lectus malesuada elementum elementum. Pellentesque at iaculis ex, vitae semper erat. Nulla eu justo commodo velit vulputate viverra pharetra sit amet nunc. Maecenas imperdiet vehicula metus, ut rutrum lorem venenatis nec. Duis semper pharetra mi. Vestibulum eget erat eget tortor tempor rutrum ut id nisl.',
]
