schema:
  - 'https://api.storipress.dev/graphql'
documents: 'src/graphql/**/*.gql'
extensions:
  codegen:
    hooks:
      afterAllFileWrite:
        - yarn prettier --write
    config:
      documentVariableSuffix: ''
    generates:
      src/generated/graphql.schema.json:
        plugins:
          - introspection
      src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - fragment-matcher
          - typed-document-node
