on:
  push:
    branches:
      - dev

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-22.04
    env:
      NODE_OPTIONS: --max-old-space-size=6144
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@storipress/core-mono'
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '18'
          cache: yarn
      - name: release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git branch release/${{ steps.release.outputs.tag_name }}
          git push origin release/${{ steps.release.outputs.tag_name }}
          git reset --hard release/${{ steps.release.outputs.tag_name }}
          git switch -c main
          git reset --hard release/${{ steps.release.outputs.tag_name }}
          git push -f origin main
          git switch dev
      - name: build release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          yarn install
          cd packages/builder
          yarn build --mode dev
          tar -Jcf builder-dev.tar.xz dist
          rm -rf dist
          yarn build --mode staging
          tar -Jcf builder-staging.tar.xz dist
          rm -rf dist
          yarn build --mode production
          tar -Jcf builder-production.tar.xz dist
      - name: upload assets
        if: ${{ steps.release.outputs.release_created }}
        uses: echapmanFromBunnings/upload-release-assets@1.3
        with:
          releaseTag: ${{ steps.release.outputs.tag_name }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          files: |
            packages/builder/builder-dev.tar.xz
            packages/builder/builder-staging.tar.xz
            packages/builder/builder-production.tar.xz
